const winAudioFiles = [
    "AnyConv.com__01ア゛.ogg",
    "AnyConv.com__02ア！？.ogg",
    "AnyConv.com__03あ！？.ogg",
    "AnyConv.com__04あ….ogg",
    "AnyConv.com__06あ…っ？.ogg",
    "AnyConv.com__07ア…ッ２.ogg",
    "AnyConv.com__08あ？.ogg",
    "AnyConv.com__09ア゛？.ogg",
    "AnyConv.com__100うぎゅう (1).ogg",
    "AnyConv.com__100うぎゅう.ogg",
    "AnyConv.com__101うぎゅう….ogg",
    "AnyConv.com__102うく…っ.ogg",
    "AnyConv.com__103うく…っ！？.ogg",
    "AnyConv.com__104うくぅ…っ.ogg",
    "AnyConv.com__105うぐぅっ.ogg",
    "AnyConv.com__106ヴッ.ogg",
    "AnyConv.com__107う゛っ (1).ogg",
    "AnyConv.com__107う゛っ.ogg",
    "AnyConv.com__108ウッ！？.ogg",
    "AnyConv.com__109うっ！？.ogg",
    "AnyConv.com__10あ゛？.ogg",
    "AnyConv.com__110うひぃっ.ogg",
    "AnyConv.com__111うひっ！？.ogg",
    "AnyConv.com__112うぶっ.ogg",
    "AnyConv.com__113うぷっ.ogg",
    "AnyConv.com__114えぁ…っ.ogg",
    "AnyConv.com__115えっち！！.ogg",
    "AnyConv.com__116おくきたぁ.ogg",
    "AnyConv.com__117おくだめぇっ (1).ogg",
    "AnyConv.com__117おくだめぇっ.ogg",
    "AnyConv.com__118オッ.ogg",
    "AnyConv.com__119おひぃっ.ogg",
    "AnyConv.com__11あ゛～～～….ogg",
    "AnyConv.com__121お゛ほっ！？.ogg",
    "AnyConv.com__122きてぇ！.ogg",
    "AnyConv.com__123キャア.ogg",
    "AnyConv.com__125きゃうん！？.ogg",
    "AnyConv.com__126きゃうんっ.ogg",
    "AnyConv.com__128くぅん….ogg",
    "AnyConv.com__129くぅん…っ.ogg",
    "AnyConv.com__12あ～～～…ん.ogg",
    "AnyConv.com__131ここすきぃっ (1).ogg",
    "AnyConv.com__131ここすきぃっ.ogg",
    "AnyConv.com__132ごめんなさいっ.ogg",
    "AnyConv.com__133これイイッ.ogg",
    "AnyConv.com__135こんなの無理ィ….ogg",
    "AnyConv.com__136そこ…っ.ogg",
    "AnyConv.com__137そこ…っ！.ogg",
    "AnyConv.com__138それすきぃっ (1).ogg",
    "AnyConv.com__138それすきぃっ.ogg",
    "AnyConv.com__139それすきっ.ogg",
    "AnyConv.com__13アァ…２.ogg",
    "AnyConv.com__140だいすきっ.ogg",
    "AnyConv.com__142だめぇ.ogg",
    "AnyConv.com__143ダメェッ.ogg",
    "AnyConv.com__144なあ゛っ.ogg",
    "AnyConv.com__145な゛あ゛っ！？.ogg",
    "AnyConv.com__146はぅぅん.ogg",
    "AnyConv.com__147はうっ！.ogg",
    "AnyConv.com__148はふぅ.ogg",
    "AnyConv.com__149はふぅん.ogg",
    "AnyConv.com__14あぁ…２.ogg",
    "AnyConv.com__150はむっ.ogg",
    "AnyConv.com__151ひ…２.ogg",
    "AnyConv.com__152ひぃ！ (1).ogg",
    "AnyConv.com__152ひぃ！.ogg",
    "AnyConv.com__153ヒィ….ogg",
    "AnyConv.com__154ひぎぃぃぃぃぃ (1).ogg",
    "AnyConv.com__154ひぎぃぃぃぃぃ.ogg",
    "AnyConv.com__155ひぎぃっ！ (1).ogg",
    "AnyConv.com__155ひぎぃっ！.ogg",
    "AnyConv.com__156ヒッ！.ogg",
    "AnyConv.com__157ひっ！？ (1).ogg",
    "AnyConv.com__157ひっ！？.ogg",
    "AnyConv.com__158フッ (1).ogg",
    "AnyConv.com__158フッ.ogg",
    "AnyConv.com__159ふっ.ogg",
    "AnyConv.com__160まって….ogg",
    "AnyConv.com__161みて…２.ogg",
    "AnyConv.com__162みるな！ (1).ogg",
    "AnyConv.com__162みるな！.ogg",
    "AnyConv.com__163みるな…！.ogg",
    "AnyConv.com__164む～～っっ (1).ogg",
    "AnyConv.com__164む～～っっ.ogg",
    "AnyConv.com__166ムグゥ！.ogg",
    "AnyConv.com__167むぐぅ！？.ogg",
    "AnyConv.com__168ムリ！.ogg",
    "AnyConv.com__169むり…っ.ogg",
    "AnyConv.com__16あぁ…っ.ogg",
    "AnyConv.com__170もういやぁっ.ogg",
    "AnyConv.com__171もうだめ (1).ogg",
    "AnyConv.com__171もうだめ.ogg",
    "AnyConv.com__172もうだめぇぇぇぇ！！.ogg",
    "AnyConv.com__173もうダメッ.ogg",
    "AnyConv.com__174もがっ.ogg",
    "AnyConv.com__175もがっ！？.ogg",
    "AnyConv.com__176やぁっ.ogg",
    "AnyConv.com__177やぁん！.ogg",
    "AnyConv.com__178やめて…っ.ogg",
    "AnyConv.com__179やらあああああっ！！.ogg",
    "AnyConv.com__17ああ…っ (1).ogg",
    "AnyConv.com__17ああ…っ.ogg",
    "AnyConv.com__180ん….ogg",
    "AnyConv.com__181んぁっ２.ogg",
    "AnyConv.com__182んおおっ.ogg",
    "AnyConv.com__183んお゛お゛っ！？.ogg",
    "AnyConv.com__184んくぅっ.ogg",
    "AnyConv.com__185んぐぅっ.ogg",
    "AnyConv.com__186ん゛っ.ogg",
    "AnyConv.com__187ンッ２.ogg",
    "AnyConv.com__188んぶっ.ogg",
    "AnyConv.com__189んへぇ….ogg",
    "AnyConv.com__18あ゛あ゛あ゛あ゛あ゛！！！.ogg",
    "AnyConv.com__190奥だめっ.ogg",
    "AnyConv.com__191許してぇ….ogg",
    "AnyConv.com__192見ちゃだめ.ogg",
    "AnyConv.com__193見ちゃダメェ！.ogg",
    "AnyConv.com__194見てっ.ogg",
    "AnyConv.com__196見るなぁ…っ (1).ogg",
    "AnyConv.com__196見るなぁ…っ.ogg",
    "AnyConv.com__197見るなぁ…っ！ (1).ogg",
    "AnyConv.com__197見るなぁ…っ！.ogg",
    "AnyConv.com__198無理ィ！.ogg",
    "AnyConv.com__199無理だからぁっ.ogg",
    "AnyConv.com__19あぁっ.ogg",
    "AnyConv.com__20アアッ.ogg",
    "AnyConv.com__21あぁっ？.ogg",
    "AnyConv.com__22あぁっ２ (1).ogg",
    "AnyConv.com__22あぁっ２.ogg",
    "AnyConv.com__23アァン.ogg",
    "AnyConv.com__24あぁん…っ.ogg",
    "AnyConv.com__26あぁんっ.ogg",
    "AnyConv.com__27あう～～～っっ.ogg",
    "AnyConv.com__28あうううんっ.ogg",
    "AnyConv.com__29あうっ！.ogg",
    "AnyConv.com__30あぅんっ.ogg",
    "AnyConv.com__31あぇ….ogg",
    "AnyConv.com__32あぇっ？.ogg",
    "AnyConv.com__33あぐあぐ.ogg",
    "AnyConv.com__34あぐぅ.ogg",
    "AnyConv.com__35あぐぅっ.ogg",
    "AnyConv.com__36あぐぅっ！？.ogg",
    "AnyConv.com__37あぐっ！？.ogg",
    "AnyConv.com__38あっ.ogg",
    "AnyConv.com__39アッ！？.ogg",
    "AnyConv.com__40あっ！？.ogg",
    "AnyConv.com__41あっ！？2.ogg",
    "AnyConv.com__42ア゛ッ！？.ogg",
    "AnyConv.com__43あ゛っ！？２.ogg",
    "AnyConv.com__44アッ！２.ogg",
    "AnyConv.com__45ア゛ッ！？２.ogg",
    "AnyConv.com__46あっ？.ogg",
    "AnyConv.com__48あっ２.ogg",
    "AnyConv.com__49ア゛ッ２.ogg",
    "AnyConv.com__50あ゛っ２.ogg",
    "AnyConv.com__51あ゛っお゛っ.ogg",
    "AnyConv.com__52あひっ.ogg",
    "AnyConv.com__53あひっ！？.ogg",
    "AnyConv.com__54あふ.ogg",
    "AnyConv.com__55あふ….ogg",
    "AnyConv.com__56あふっ.ogg",
    "AnyConv.com__57あふん.ogg",
    "AnyConv.com__58あへ.ogg",
    "AnyConv.com__59あへぇ.ogg",
    "AnyConv.com__60あむ.ogg",
    "AnyConv.com__61_1あむあむ.ogg",
    "AnyConv.com__61_2あむあむ.ogg",
    "AnyConv.com__62あむっ.ogg",
    "AnyConv.com__63アン (1).ogg",
    "AnyConv.com__63アン.ogg",
    "AnyConv.com__64あん (1).ogg",
    "AnyConv.com__64あん.ogg",
    "AnyConv.com__65アン….ogg",
    "AnyConv.com__66い…っ.ogg",
    "AnyConv.com__67いぁっ.ogg",
    "AnyConv.com__68いあ゛っ.ogg",
    "AnyConv.com__69イかせてぇ！.ogg",
    "AnyConv.com__70イかせてぇっ (1).ogg",
    "AnyConv.com__70イかせてぇっ.ogg",
    "AnyConv.com__71いかせてぇっ (1).ogg",
    "AnyConv.com__71いかせてぇっ.ogg",
    "AnyConv.com__72いぎぃっ.ogg",
    "AnyConv.com__73い゛ぎぃっ.ogg",
    "AnyConv.com__75い゛ぎだい゛っっ (1).ogg",
    "AnyConv.com__75い゛ぎだい゛っっ.ogg",
    "AnyConv.com__77いぎっ！？.ogg",
    "AnyConv.com__78いぎゅっ.ogg",
    "AnyConv.com__79イグ～～～ッ.ogg",
    "AnyConv.com__80イグイグイグイグ！！.ogg",
    "AnyConv.com__81イグゥ.ogg",
    "AnyConv.com__82イグゥゥゥゥゥ！！.ogg",
    "AnyConv.com__83いぐぅぅぅぅぅ！！！.ogg",
    "AnyConv.com__84いぐぅぅぅぅぅ！！.ogg",
    "AnyConv.com__85イグゥッ.ogg",
    "AnyConv.com__86イ゛グッ.ogg",
    "AnyConv.com__87い゛ぐっ.ogg",
    "AnyConv.com__88イクッ２.ogg",
    "AnyConv.com__89いくっ２.ogg",
    "AnyConv.com__90イ゛グッッ (1).ogg",
    "AnyConv.com__90イ゛グッッ.ogg",
    "AnyConv.com__91いっ.ogg",
    "AnyConv.com__92イっちゃった….ogg",
    "AnyConv.com__93いっぱい出してぇ！！.ogg",
    "AnyConv.com__94い゛やあああああ！！！.ogg",
    "AnyConv.com__95いやぁっ.ogg",
    "AnyConv.com__96いやあっ！！！.ogg",
    "AnyConv.com__97いやっ.ogg",
    "AnyConv.com__98うぎぃ！？.ogg",
    "AnyConv.com__99うぎぃっ！？.ogg"
];
