// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
  {
    "description": "プラグイン共通基盤（PictureCallCommon等の必須ライブラリ）",
    "name": "PluginCommonBase",
    "status": true
  },
  {
    "description": "ピクチャをクリック可能にします。",
    "name": "ButtonPicture",
    "status": true
  },
  {
    "description": "ピクチャのボタン化プラグイン",
    "name": "PictureCallCommon",
    "status": true
  },
  {
    "description": "文字をピクチャとして表示します。",
    "name": "TextPicture",
    "status": true
  },
  {
    "description": "クリッカーエンジン (原因切り分けのため一時停止)",
    "name": "KyokoClickerEngine",
    "status": false
  },
  {
    "description": "探索・謎解き支援プラグイン - 接近検知・暗証番号パネル・発見ポップアップ",
    "name": "SimpleSearchSystem",
    "status": true
  },
  {
    "description": "強制画面表示＆診断デバッグ",
    "name": "EmergencyDebug",
    "status": true
  }
];
